[2025-07-07 23:36:30] Exception in maybe_run_webcmd:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 3102, in maybe_run_webcmd
    cmd = json.load(f)
          ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2025-07-07 23:35:39] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1111, in process_command
    code = int(code_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5400P5308I6000'

[2025-07-07 23:35:20] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1111, in process_command
    code = int(code_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5400P5308I6000'

[2025-07-07 23:03:45] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1105, in process_command
    code = int(code_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5400P5300'

[2025-07-07 21:23:24] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1054, in process_command
    code = int(code_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5300A5400i6000'

[2025-07-07 21:23:24] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1054, in process_command
    code = int(code_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5300A5400i6000'

[2025-07-07 21:23:24] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1054, in process_command
    code = int(code_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5300A5400i6000'

[2025-07-07 21:23:23] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1054, in process_command
    code = int(code_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5300A5400i6000'

[2025-07-07 21:23:22] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1054, in process_command
    code = int(code_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5300A5400i6000'

[2025-07-07 20:54:27] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1070, in process_command
    code = int(code_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5300A5400i6000'

[2025-07-07 20:54:26] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1070, in process_command
    code = int(code_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5300A5400i6000'

[2025-07-07 20:54:18] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1070, in process_command
    code = int(code_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5300A5400i6000'

[2025-07-07 20:19:26] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1087, in process_command
    play_interrupt_to_another(base_filename, str(alt_code))
  File "/home/drx/DRX/drx_main.py", line 2040, in play_interrupt_to_another
    interrupted = play_single_wav(
                  ^^^^^^^^^^^^^^^^
TypeError: play_single_wav() got an unexpected keyword argument 'display_name'

[2025-07-07 20:19:24] Exception in process_command:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 1087, in process_command
    play_interrupt_to_another(base_filename, str(alt_code))
  File "/home/drx/DRX/drx_main.py", line 2040, in play_interrupt_to_another
    interrupted = play_single_wav(
                  ^^^^^^^^^^^^^^^^
TypeError: play_single_wav() got an unexpected keyword argument 'display_name'

[2025-07-07 20:11:19] Exception in maybe_run_webcmd:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 2953, in maybe_run_webcmd
    cmd = json.load(f)
          ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

