[2025-07-10 13:43:14] Exception in main:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 4029, in main
    threading.Thread(target=monitor_tot_cos, daemon=True).start()
                            ^^^^^^^^^^^^^^^
NameError: name 'monitor_tot_cos' is not defined

[2025-07-10 13:43:00] Exception in main:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 4029, in main
    threading.Thread(target=monitor_tot_cos, daemon=True).start()
                            ^^^^^^^^^^^^^^^
NameError: name 'monitor_tot_cos' is not defined

[2025-07-10 13:31:01] Exception in main:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 4015, in main
    threading.Thread(target=monitor_tot_cos, daemon=True).start()
                            ^^^^^^^^^^^^^^^
NameError: name 'monitor_tot_cos' is not defined

[2025-07-10 13:30:36] Exception in main:
Traceback (most recent call last):
  File "/home/drx/DRX/drx_main.py", line 4015, in main
    threading.Thread(target=monitor_tot_cos, daemon=True).start()
                            ^^^^^^^^^^^^^^^
NameError: name 'monitor_tot_cos' is not defined

